const journeyActionTypes = {
  TRIP_DIRECTIONS_REQUEST: "TRIP_DIRECTIONS_REQUEST",
  INPUTS_UPDATE_AUTOSUGGEST: "INPUTS_UPDATE_AUTOSUGGEST",
  TRIPS_CREATE_TRIP: "TRIPS_CREATE_TRIP",
  UPDATE_INPUTS: "UPDATE_INPUTS",
  NOTIFICATION_UPDATE_SPINNER: "NOTIFICATION_UPDATE_SPINNER",
  INPUTS_UPDATE_AUTOSUGGEST_DESTINATION_SUGGESTIONS:
    "INPUTS_UPDATE_AUTOSUGGEST_DESTINATION_SUGGESTIONS",
  INPUTS_UPDATE_AUTOSUGGEST_ORIGIN_SUGGESTIONS:
    "INPUTS_UPDATE_AUTOSUGGEST_ORIGIN_SUGGESTIONS",
  INPUTS_UPDATE_AUTOSUGGEST_DESTINATION_VALUE:
    "INPUTS_UPDATE_AUTOSUGGEST_DESTINATION_VALUE",
  INPUTS_UPDATE_AUTOSUGGEST_ORIGIN_VALUE:
    "INPUTS_UPDATE_AUTOSUGGEST_ORIGIN_VALUE",
  SUGGESTED_TRIPS_REQUEST: "SUGGESTED_TRIPS_REQUEST",
  SUGGESTED_CITIES_REQUEST: "SUGGESTED_CITIES_REQUEST",
  SHIFT_JOURNEY_PANEL_DATE_RANGE: "SHIFT_JOURNEY_PANEL_DATE_RANGE",
  ZOOM_JOURNEY_PANEL_DATE_RANGE: "ZOOM_JOURNEY_PANEL_DATE_RANGE"
};
export default journeyActionTypes;
