const journeyActionTypes = {
  TRIP_DIRECTIONS_REQUEST: "TRIP_DIRECTIONS_REQUEST",
  INPUTS_UPDATE_AUTOSUGGEST: "INPUTS_UPDATE_AUTOSUGGEST",
  TRIPS_CREATE_TRIP: "TRIPS_CREATE_TRIP",
  UPDATE_INPUTS: "UPDATE_INPUTS",
  NOTIFICATION_UPDATE_SPINNER: "NOTIFICATION_UPDATE_SPINNER"
};
export default journeyActionTypes;
